config/routes.rb
MightbuyBusiness::Application.routes.draw do
  devise_for :business_staffs, controllers: {
      registrations: 'registrations'
  }

  resource :business do
    collection do
      get :complete_profile
      get :profile
      put :update_profile
    end
    resources :business_staffs, module: "business"
  end

  resources :products do
    resource :deal
  end

  resources :topics

  resources :timeline
  resources :customers
  resources :leads do
    resources :topics, only: [:destroy]
  end

  resource  :retail
  resources :retail_leads do
    get 'photo', on: :member
  end
  resource  :business_config, only: [:edit, :update]

  root :to => "welcome#index"
  match "/contact" => "welcome#contact"
  match "/about" => "welcome#about"
  match "/terms" => "welcome#terms"
  match "/pricing" => "welcome#pricing"
  match "/help" => "welcome#help"

end

app/controllers/business/business_staffs_controller.rb
class Business::BusinessStaffsController < ApplicationController
  layout 'business_with_sidebar'
  before_filter :find_business

  def index
    @business_staffs = @business.business_staffs.page(params[:page]).per(10)
    @business_staff = BusinessStaff.new()
  end

  def create
    business_staff_params = params[:business_staff]
    business_staff_params.update(password_confirmation: business_staff_params[:password], business: @business)
    business_staff = BusinessStaff.create(business_staff_params)
    if business_staff.errors.empty?
      flash[:notice] = "Successfully added"
    else
      flash[:error] = business_staff.errors.full_messages.first
    end
    redirect_to business_business_staffs_path
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  skip_before_filter :authenticate_business_staff!, only: [:new, :create, :foo]
  before_filter :find_business, only: [:show, :complete_profile, :update, :profile, :update_profile]
  respond_to :html, :js

  layout :choose_layout

  def new
    @business_user = BusinessUser.new()
  end

  def create
    @business_user = BusinessUser.new(params[:business_user])
    if @business_user.save
      sign_in @business_user.business_staff, bypass: true
      redirect_to root_path
    else
      flash[:error] = @business_user.errors.full_messages.join(" ")
      render :action => "new"
    end
  end

  def show
    unless @business.url_verified
      redirect_to complete_profile_business_path
    else
      render layout: 'business_with_sidebar'
    end
  end

  def update
    if @business.update_attributes(params[:business])
      @business.update_column('profile_updated',true)
      flash[:notice] = "Updated business details successfully, we need to verify your business url before you can proceed."
    end
    @business.reload

    respond_with(@business) do |format|
      format.html { render action: "complete_profile" }
    end
  end

  def update_profile
    if @business.update_attributes(params[:business])
      flash[:notice] = "Profile update"
    else
      flash[:error] = "Error updating profile"
    end
    redirect_to profile_business_path
  end

  def complete_profile
    if @business.business_urls.empty?
      @business.business_urls.build()
    end
  end

  def profile
    render layout: 'business_with_sidebar'
  end

  private
  def choose_layout
    if ['new','create'].include?(action_name)
      'application'
    else
      'business'
    end
  end
end

app/helpers/business/business_staffs_helper.rb
module Business::BusinessStaffsHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
  def verification_alert_class
    if @business.profile_updated
      "verify-alert"
    else
      "verify-alert hide"
    end
  end

  def save_profile_button_class
    if @business.profile_updated
      "btn btn-red w230 m-auto disabled"
    else
      "btn btn-red w230 m-auto"
    end
  end

  def business_form_logo_url_helper(business)
    if business.logo
      business.logo.thumb('x80').url
    else
      "/assets/company-logo.gif"
    end
  end
end

app/views/businesses/_business_form.html.erb
<div id="business-logo-form-wrapper">
  <%= render partial: "business_logo_form", locals: { business: @business } -%>
</div>

<%= form_for(@business, :url => action_url) do |f| -%>
  <div class="row">
    <div class="span4">
      <label>Business Name</label>
      <%= f.text_field :name -%>

      <label>Website Address</label>
      <div class='business-urls'>
        <%= f.fields_for :business_urls do |business_url| -%>
          <div>
            <%= business_url.text_field :domain -%>

            <a href="javascript:void(0);" class="btn btn-yellow btn-add more-url">
              <i class="icon-plus"></i>
            </a>
          </div>
        <% end -%>
      </div>

    <label>Address</label>
    <%= f.text_area :address -%>
  </div>
  <div class="span4">
    <label>Email Address</label>
    <%= f.text_field :email -%>

    <label>Phone</label>
    <%= f.text_field :phone -%>

    <label>Twitter Handle</label>
    <%= f.text_field :twitter_handle -%>

    <label>Facebook Website Address</label>
    <%= f.text_field :facebook_url -%>

    <label>Pinterest</label>
    <%= f.text_field :pinterest_handle -%>
  </div>
</div>

<button class="<%= save_profile_button_class -%>" type="submit">
  Save Profile Information
</button>

<% end -%>

app/views/businesses/_business_logo_form.html.erb
<%= form_for(business, url: business_path, html: { id: "business_logo_form", multipart: true }, remote: true) do |f| -%>
<div class="row">
  <div class="span8">
    <legend>
      Profile Information
    </legend>
    <div class="company-logo">
      <%= image_tag(business_form_logo_url_helper(business), height: 80) -%>
      <div class="loader hide"></div>
    </div>
    <%= f.file_field :logo, style: "display: none" -%>
    <%= f.hidden_field :retained_logo %>
    <div id="business_logo_url_wrapper" class="hide">
      <h4> Paste a URL for Web Image here </h4>
      <hr class="m-bot10 m-top10"/>
      <div class="row-fluid">
        <div class="span2 a-right">
          URL:
        </div>
        <div class="span10">
          <%= f.text_field :logo_url %>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span2">
          &nbsp;
        </div>
        <div class="span10">
          <button class="btn btn-yellow save-url" type="button">
            Upload
          </button>
        </div>
      </div>
    </div>
    <div class="pull-left">
      <div>
        <button id="logo-url-button" class="btn btn-yellow w100 pull-left" type="button">
          Use Image
          <br/>
          From Web
        </button>
      </div>
      <div>
        <button id="logo-upload-button" class="btn btn-yellow w100 pull-left clear-left" type="submit">
          Upload
        </button>
      </div>
    </div>
  </div>
</div>
<% end -%>

app/views/businesses/_signup_form.html.erb
<fieldset>
  <div class="row-fluid">
    <div class="span6">
      <label>Full Name of User</label>
      <%= f.text_field :fullname -%>
    </div>
    <div class="span6">
      <label>Business Name</label>
      <%= f.text_field :business_name -%>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span6">
      <label>Email</label>
      <%= f.text_field :email -%>
    </div>
    <div class="span6">
      <label>Business URL</label>
      <%= f.text_field :business_url -%>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span6">
      <label>Password</label>
      <%= f.password_field :password -%>
    </div>
    <div class="span6">
      <label>Password Confirmation</label>
      <%= f.password_field :password_confirmation -%>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span6">
      <label>Phone number</label>
      <%= f.text_field :phone_number -%>
    </div>
    <div class="span6">
      <button class="btn btn-yellow w80 pull-right" type="submit">
        Signup
      </button>
    </div>
  </div>
  <hr class="m-bot0">
</fieldset>

app/views/businesses/complete_profile.html.erb
<div class="row">
  <div class="span12">
    <h3 class="page-title">
      Welcome to MightBuy for Business
      <%= link_to("logout", destroy_business_staff_session_path, method: :delete, :class=>"link-white") -%>
    </h3>
    <p class="sub-title">
      Please complete the profile information below to get started.
    </p>
    <div class="<%= verification_alert_class -%>">
      To ensure your Website Address/ Business URL is valid. Mightbuy Admin will verify it and get back to you soon.
    </div>
  </div>
</div>
<div class="row">
  <div class="span9 offset2">
    <div class="profile-form">
      <%= render partial: "business_form", locals: { action_url: business_path } -%>
    </div>
  </div>
</div>

app/views/businesses/foo.html.erb
<div class="row">
  <div class="span12">
    <h3 class="page-title"> Welcome to MightBuy for Business </h3>
    <p class="sub-title">
      Please complete the profile information below to get started.
    </p>
  </div>
</div>
<div class="row">
  <div class="span9 offset2">
    <div class="profile-form">
      <form action="">
        <div class="row">
          <div class="span8">
            <legend>
              Profile Information
            </legend>
            <img class="img-polaroid pull-left" src="/assets/company-logo.gif" />
            <div class="pull-left">
              <div>
                <button class="btn btn-yellow w100 pull-left" type="submit">
                  Use Image
                  <br/>
                  From Web
                </button>
              </div>
              <div>
                <button class="btn btn-yellow w100 pull-left clear-left" type="submit">
                  Upload
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="span4">
            <label>Business Name</label>
            <input type="text" />
            <label>Website Address</label>
            <input type="text" />
            <button class="btn btn-yellow btn-add" type="submit">
              <i class="icon-plus"></i>
            </button>
            <label>Phone</label>
            <input type="text" />
            <button class="btn btn-yellow btn-add" type="submit">
              <i class="icon-plus"></i>
            </button>
            <label>Address</label>
            <input type="text" />
            <button class="btn btn-yellow btn-add" type="submit">
              <i class="icon-plus"></i>
            </button>
          </div>
          <div class="span4">
            <label>Email Address</label>
            <input type="text" />
            <button class="btn btn-yellow btn-add" type="submit">
              <i class="icon-plus"></i>
            </button>
            <label>Twitter Handle</label>
            <input type="text" />
            <button class="btn btn-yellow btn-add" type="submit">
              <i class="icon-plus"></i>
            </button>
            <label>Facebook Website Address</label>
            <input type="text" />
            <button class="btn btn-yellow btn-add" type="submit">
              <i class="icon-plus"></i>
            </button>
            <label>Pinterest</label>
            <input type="text" />
            <button class="btn btn-yellow btn-add" type="submit">
              <i class="icon-plus"></i>
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<button class="btn btn-red w230 m-auto" type="submit">
  Save Profile Information
</button>

app/views/businesses/new.html.erb
<div class="container silhouette-bg">
  <div class="trapezoid-bg hidden-phone"></div>
  <div class="content signup">
    <div class="top-gradient"></div>
    <div class="row">
      <div class="login-form">
        <h2 class="logo signup">MightBuy.<span>for business</span></h2>
        <hr>
        <%= form_for(@business_user, :url => business_path) do |f|-%>
          <%= render :partial => "signup_form", :locals => {:f => f} -%>
        <% end -%>
      </div>
    </div>
    <div class="footer">
      <div class="row-fluid">
        <div class="span6 b-right-dark">
          <div class="c-holder-left">
            <%= link_to(new_business_staff_password_path) do -%>
              <span class="normal-font">Password recovery</span>
              <span class="tiny-font">You forgot your password?</span>
            <% end -%>
          </div>
        </div>
        <div class="span6 b-right-light">
          <div class="c-holder-right">
            <%= link_to(new_business_staff_session_path) do -%>
              <span class="normal-font">Sign In</span> <span class="tiny-font">Already a member, login here!</span>
            <% end -%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/businesses/profile.html.erb
<div class="span9 bg-dark unevenheights account-profile">
  <h3 class="page-title align-right"> Profile Information </h3>
  <%= render partial: "business_form", locals: { action_url: update_profile_business_path } -%>
</div>

app/views/businesses/show.html.erb
<div class="span9 bg-dark unevenheights">
  <h3 class="page-title align-right"> Dashboard </h3>
  <div class="dashboard-container">
    <div class="row-fluid">
      <!-- ------Column 1------------------------------------------------------------------------------------------------------------------------------------------------ -->
      <div class="span4">
        <div class="dash-count">
          <div class="dash-num">
            14<small>Products</small>
          </div>
        </div>
        <div class="dash-caption unevenheights-caption">
          &nbsp;
        </div>
        <div class="more-link">
          <a href="#" class="btn btn-danger"> <i class="icon-white icon-plus"></i> Add more </a>
        </div>
        <div class="value uneven-val">
          <div class="text-success min-height-val">
            $999,999.00 <small>Product value <i>?</i></small>
          </div>
        </div>
        <div class="changes">
          <span class="num">18</span>
          <span class="text"><b class="percent">%</b> Change<small>from last month</small></span>
          <span class="arrow-up">⬆</span>
          <span class="arrow-down hide">⬇</span>
        </div>
      </div>
      <!-- --------- Column 2--------------------------------------------------------------------------------------------------------------------------------------------- -->
      <div class="span4">
        <div class="dash-count">
          <div class="dash-num">
            12<small>People</small>
          </div>
        </div>
        <div class="dash-caption unevenheights-caption">
          Added your product to MighBuy.it
        </div>
        <div class="more-link">
          <a href="#" class="btn btn-danger"> <i class="icon-white icon-plus"></i> Invite more </a>
        </div>
        <div class="value uneven-val">
          <div class="min-height-val">
            4500 <small>Social Reach <i>?</i></small>
          </div>
          <hr/>
          <div class="min-height-val">
            311 <small>Page Views <i>?</i></small>
          </div>
          <hr/>
          <div class="min-height-val">
            27 <small>Votes + Referals <i>?</i></small>
          </div>
        </div>
        <div class="changes">
          <span class="num">18</span>
          <span class="text"><b class="percent">%</b> Change<small>from last month</small></span>
          <span class="arrow-up">⬆</span>
          <span class="arrow-down hide">⬇</span>
        </div>
      </div>
      <!-- -------- Column 3---------------------------------------------------------------------------------------------------------------------------------------------- -->
      <div class="span4">
        <div class="dash-count">
          <div class="dash-num">
            3<small>Leads</small>
          </div>
        </div>
        <div class="dash-caption unevenheights-caption">
          &nbsp;
        </div>
        <div class="more-link">
          <a href="#" class="btn btn-danger"> <i class="icon-white icon-plus"></i> Invite more </a>
        </div>
        <div class="value uneven-val">
          <div class="min-height-val">
            2 <small>Accepted</small>
          </div>
          <hr/>
          <div class="text-success min-height-val">
            $1400 <small>Closed Leads</small>
          </div>
        </div>
        <div class="changes">
          <span class="num">18</span>
          <span class="text"><b class="percent">%</b> Change<small>from last month</small></span>
          <span class="arrow-up">⬆</span>
          <span class="arrow-down hide">⬇</span>
        </div>
      </div>
      <!-- ---------Column 3 ends here--------------------------------------------------------------------------------------------------------------------------------------------- -->
    </div>
  </div>
</div>

app/views/businesses/update.js.erb
<%= remotipart_response do -%>
  $("#business-logo-form-wrapper").html(
    "<%= escape_javascript(render partial: 'business_logo_form', locals: { business: @business }) -%>");
  Mightbuy.logoUploader = new Mightbuy.LogoUploader();
  $(document).trigger('close.facebox')
<% end -%>