config/routes.rb
MightbuyBusiness::Application.routes.draw do
  devise_for :business_staffs, controllers: {
      registrations: 'registrations'
  }

  resource :business do
    collection do
      get :complete_profile
      get :profile
      put :update_profile
    end
    resources :business_staffs, module: "business"
  end

  resources :products do
    resource :deal
  end

  resources :topics

  resources :timeline
  resources :customers
  resources :leads do
    resources :topics, only: [:destroy]
  end

  resource  :retail
  resources :retail_leads do
    get 'photo', on: :member
  end
  resource  :business_config, only: [:edit, :update]

  root :to => "welcome#index"
  match "/contact" => "welcome#contact"
  match "/about" => "welcome#about"
  match "/terms" => "welcome#terms"
  match "/pricing" => "welcome#pricing"
  match "/help" => "welcome#help"

end

app/views/shares/_business_sidebar.html.erb
<div class="span3 hidden-phone">
  <div class="user-info">
    <div class="customer-brand">
      <%= @business.name -%>
    </div>
    <div class="customer-name">
      <% if current_business_staff.name and not current_business_staff.name.empty? -%>
      <div>
        Hello <span><%= current_business_staff.name -%></span>
      </div>
      <% end -%>
      <%= link_to("logout",destroy_business_staff_session_path, method: :delete) -%>
    </div>
  </div>

  <div class="menu-title">
    Dashboard
  </div>
  <ul class="nav nav-list">
    <li class="<%= active_tab_class('timeline') -%>">
      <%= link_to(timeline_index_path) do -%>
         Activity
        <div class="arrow-left"></div>
      <% end -%>
    </li>
  </ul>

  <div class="menu-title">
    Customers
  </div>
  <ul class="nav nav-list">
    <li class="<%= active_tab_class('customers') -%>">
      <%= link_to(customers_path) do -%>
        Potential
        <div class="arrow-left"></div>
      <% end -%>
    </li>
    <li class="<%= active_tab_class('leads') -%>">
      <%= link_to(leads_path) do -%>
        Leads
        <div class="arrow-left"></div>
      <% end -%>
    </li>
  </ul>

  <div class="menu-title">
    Business
  </div>
  <ul class="nav nav-list">
	<li class="<%= active_tab_class('businesses') -%>">
      <%= link_to(profile_business_path) do -%>
        Profile
        <div class="arrow-left"></div>
      <% end -%>
    </li>
    <li class="<%= active_tab_class('products') -%>">
      <%= link_to(products_path) do -%>
        Products
        <div class="arrow-left"></div>
      <% end -%>
    </li>
    <li class="<%= active_tab_class('business_configs') -%>">
      <%= link_to(@business.business_config ? edit_business_config_path : new_business_config_path) do -%>
        Retail
        <div class="arrow-left"></div>
      <% end -%>
    </li>
    <li class="<%= active_tab_class('business_staffs') -%>">
      <%= link_to(business_business_staffs_path) do -%>
        Staff
        <div class="arrow-left"></div>
      <% end -%>
    </li>
  </ul>


  <%= link_to("Your Account", edit_business_staff_registration_path, class: "other-menus") -%>
</div>

app/views/shares/_header.html.erb
<%= render partial: "partials/uservoice" -%>
<div class="header">
  <div class="header-gradient visible-phone"></div>
  <div class="z-index1">
<%- if @business.url_verified %>
    <div class="lead-capture">
        <%= link_to('Lead Capture', new_retail_lead_path, class: 'btn btn-large btn-danger') -%>
    </div>
<% end %>
    <a href="/" class="brand"> <h2 class="logo-business">MightBuy.<span>for business</span></h2> </a>
    <div class="navbar navbar-inverse">
      <button type="button" class="btn btn-navbar visible-phone" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="nav-collapse collapse visible-phone">
        <div class="hr"></div>
        <div class="user-info">
          <div class="customer-brand">
            <%= @business.name -%>
          </div>
          <div class="customer-name">
            <div>
              Hello <span><%= current_business_staff.name -%></span>
            </div>
            <%= link_to("logout",destroy_business_staff_session_path, method: :delete) -%>
          </div>
        </div>
        <div class="hr"></div>
        <ul class="nav">
          <li class="<%= active_tab_class('products') -%>">
            <%= link_to(products_path) do -%>
            Products <div class="arrow-left"></div>
            <% end -%>
          </li>
          <li class="<%= active_tab_class('customers') -%>">
            <%= link_to(customers_path) do -%>
            Potential Customers <div class="arrow-left"></div>
            <% end -%>
          </li>
          <li class="<%= active_tab_class('leads') -%>">
            <%= link_to(leads_path) do -%>
            Customers Leads <div class="arrow-left"></div>
            <% end -%>
          </li>
          <li class="<%= active_tab_class('business_configs') -%>">
            <%= link_to(@business.business_config ? edit_business_config_path : new_business_config_path) do -%>
            Lead Capture <div class="arrow-left"></div>
            <% end -%>
          </li>
          <li>
            <%= link_to("Accounts", profile_business_path) -%>
          </li>
          <li class="<%= active_tab_class('business_staffs') -%>">
            <%= link_to(business_business_staffs_path) do -%>
            Users <div class="arrow-left"></div>
            <% end -%>
          </li>
          <li>
            <a href="#">Help</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="hr"></div>

app/views/shares/_notifications.html.erb
<% if flash[:notice] -%>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] -%>
  </div>
<% end -%>

<% if flash[:info] -%>
  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:info] -%>
  </div>
<% end -%>

<% if flash[:error] or flash[:alert] -%>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:error] or flash[:alert] -%>
  </div>
<% end -%>

app/views/shares/_social_plugin.html.erb
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
  <a class="addthis_button_preferred_1"></a>
  <a class="addthis_button_preferred_2"></a>
</div>
<script type="text/javascript">
  var addthis_config = {"data_track_addressbar":false, "services_expanded":"twitter,facebook"};
  var addthis_share = {"url": "<%= @lead_invite.topic_url %>", "title": "<%= @lead_invite.topic_url %>" };
</script>
<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-50aa1e80249de8c1"></script>
<!-- AddThis Button END -->