config/routes.rb
MightbuyBusiness::Application.routes.draw do
  devise_for :business_staffs, controllers: {
      registrations: 'registrations'
  }

  resource :business do
    collection do
      get :complete_profile
      get :profile
      put :update_profile
    end
    resources :business_staffs, module: "business"
  end

  resources :products do
    resource :deal
  end

  resources :topics

  resources :timeline
  resources :customers
  resources :leads do
    resources :topics, only: [:destroy]
  end

  resource  :retail
  resources :retail_leads do
    get 'photo', on: :member
  end
  resource  :business_config, only: [:edit, :update]

  root :to => "welcome#index"
  match "/contact" => "welcome#contact"
  match "/about" => "welcome#about"
  match "/terms" => "welcome#terms"
  match "/pricing" => "welcome#pricing"
  match "/help" => "welcome#help"

end

app/controllers/retail_leads_controller.rb
class RetailLeadsController < ApplicationController
  skip_before_filter :authenticate_business_login!
  before_filter :find_business
  before_filter :find_customer_lead!, only: [:show, :photo, :update]
  layout 'retail'

  def show
    render_wizard
  end

  def new
    @lead = @business.customer_leads.build
    @lead.topics.build

    if @business.business_config.include_liability?
      render template: 'retail_leads/new'
    else
      render template: 'retail_leads/new_with_photo'
    end
  end

  def photo
    @lead.topics.build
  end

  def create
    @lead = @business.customer_leads.new(params[:customer_lead])

    if @lead.save!
      if @business.business_config.include_liability?
        redirect_to photo_retail_lead_path(@lead)
      else
        send_lead_invite if params[:send_email] == '1'
      end
    else
      flash[:error] = @lead.errors.full_messages.first
      render action: :new
    end
  end

  def update
    @lead.update_attributes(params[:customer_lead])

    if @lead.errors.empty? && params[:send_email] == '1'
      send_lead_invite
    end

    if @lead.errors.empty?
      flash[:notice] = "Updated Customer Lead Successfully"
    else
      flash[:notice] = @lead.errors.full_messages.first
    end
  end

  private
  def find_customer_lead!
    unless @lead = @business.customer_leads.find_by_id(params[:id])
      redirect_to new_retail_leads_path
    end
  end

  def send_lead_invite
    @lead_invite = @lead.create_invite
    @lead_invite.business_staff = current_business_staff
    @lead_invite.email_customer
  end
end

app/helpers/retail_leads_helper.rb
module RetailLeadsHelper
  def product_list_helper(business)
    @business.products.collect do |product|
      [ product.name, product.id ]
    end
  end


  def replace_variables_helper(signature, lead_invite)
    return unless signature.is_a? String

    if lead_invite.lead.product
      signature.gsub!(/{{\s*product\.name\s*}}/, lead_invite.lead.product.name)
    end

    signature
  end
end

app/views/retail_leads/_list_confirmation.html.erb
<div class="modal lead-capture hide fade" id="list-confirmation">
  <div class="modal-header">
    <button class="close" type="button" data-dismiss="modal" area-hidden="tru">
      &times
    </button>
  </div>
  <div class="modal-body">
    <div class="row-fluid">
      <h1> GREAT SUCCESS!! </h1>
    </div>
  </div>

  <div class="modal-footer">
    <a class="btn btn-danger btn-large" href="/leads"> Done </a>
  </div>

  <div class="modal-footer">
    <a class="btn btn-danger btn-large" href="/retail_leads/new?list_add=1&email=<%= lead.email -%>&name=<%= lead.name -%>&phone_number=<%= lead.phone_number-%>" > Add image </a>
  </div>

</div>

app/views/retail_leads/_modal_confirmaiton.html.erb
<div class="modal lead-capture hide fade" id="lead-confirmation">
  <div class="modal-header">
    <button class="close" type="button" data-dismiss="modal" area-hidden="tru">
      &times
    </button>
  </div>
  <div class="modal-body">
    <div class="row-fluid">
      <h1> GREAT SUCCESS!! </h1>
    </div>
  </div>

  <div class="modal-footer">
    <a class="btn btn-danger btn-large" href="/retail_leads/new"> Done </a>
  </div>


  <div class="modal-footer">
    <a class="btn btn-danger btn-large" href="/retail_leads/new?add=true&email=<%= lead.email -%>&name=<%= lead.name -%>&phone_number=<%= lead.phone_number-%>" > Add image </a>
  </div>



</div>

app/views/retail_leads/add_potato.html.erb
<div class="release-liability clearfix">
  <%= form_for @lead, url: retail_leads_path, remote: true, method: :post, html: {multipart: true, id: "photo-form"} do |f| -%>
    <div class="row-fluid">
      <div class="span12">
        <%= link_to("Logout", destroy_business_staff_session_path, method: :delete, class: 'btn btn-danger pull-right') -%>
        <%= image_tag(business_form_logo_url_helper(@business), height: 80, class: "img-polaroid pull-left m-right25") -%>
        <h1><%= @business.name -%></h1>
      </div>
    </div>
    <%= hidden_field_tag "send_email", 0 -%>

    <div class="row-fluid">
      <div class="span12">
        <div class="well">
          <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
              <td id="lead-photo-preview" valign="center" class="picture">
                &nbsp;
              </td>
            </tr>
          </table>
          <br/>

          <div class="clearfix">
            <div class="row-fluid">
              <div class="span3 hidden-phone">&nbsp;</div>
              <div class="span6 photo-upload">
                <input id="filename" type="text" class="input disabled pull-left visible-desktop" name="filename" readonly>
                <a id="fileselectbutton" class="btn btn-danger pull-left">Take Pic</a>
                <%= f.file_field :photo %>
                <%= f.hidden_field :retained_photo %>
              </div>
              <div class="span3 hidden-phone">&nbsp;</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%- if @business.business_config.include_product_select? -%>
          <div class="row-fluid">
            <div class="span12">
              <%= f.label :product_id, 'Select a Product' -%>
              <%= f.select :product_id, product_list_helper(@business) -%>
            </div>
          </div>
     <% end -%>

    <%- if @business.business_config.ask_for_description? %>
    <div class="row-fluid">
        <div class="span12">
            <%= f.label :message, 'Description' %>
            <%= f.text_area  :message, :rows=>5 %>
         </div>
    </div>
    <% end -%>

    <br/>

    <div class="row-fluid">
      <div class="span12">
        <%= f.submit 'Save', class: 'btn btn-large btn-danger', id: "photo-submit-button", disabled: 'disabled' %>
        <button class="btn btn-large btn-danger pull-right" type="button" id="photo-email-button" disabled="disabled">
          Send Now
        </button>
      </div>
    </div>
  <% end -%>
  <br/>
  <hr/>
  <small class="pull-left">powered by</small>
  <%= link_to("", "http://www.mightbuy.it", class: 'logo-small', target: '_blank') -%>
</div>

<%= render :partial => "modal_confirmaiton" -%>

app/views/retail_leads/create.js.erb
$("#flash-notifications").html("<%= escape_javascript(render partial: 'shares/notifications') -%>");
<%- flash.clear -%>

<% if @lead.errors.empty? -%>
  $(".saving-loader").hide();
  $("#lead-confirmation").modal().center();

<% end -%>



<% if params[:list_add] == "1" -%>
  $('div.release-liability').after("<%= raw escape_javascript( render :partial => 'list_confirmation', :locals => {:lead => @lead} ) 
%>");
	$('#list-confirmation').modal().center();
<% else -%>
 $('div.release-liability').after("<%= raw escape_javascript( render :partial => 'modal_confirmaiton', :locals => {:lead => @lead} )
%>");
	$('#lead-confirmation').modal().center();
<% end -%>

app/views/retail_leads/new.html.erb
<div class="new-lead release-liability clearfix">
  <%= form_for @lead, url: retail_leads_path do |f| -%>
  <div class="row-fluid">
    <div class="span12">
      <%= link_to("Logout", destroy_business_staff_session_path, method: :delete, class: 'btn btn-danger pull-right') -%>
      <%= image_tag(business_form_logo_url_helper(@business), height: 80, class: "img-polaroid pull-left m-right25") -%>
      <h1><%= @business.name -%></h1>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div class="well">
        <div class="overflow">
          <h3>Release and Waiver of Liability, Assumption of Risk, and Indemnity Agreement</h3>
          <p> <%= raw md2html(@business.business_config.liability) -%> </p>
        </div>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div id="business-liability"></div>
      <%- if @business.business_config.ask_for_name? -%>
        <%= f.label :name, 'Full Name of participant or Parent/Guardian, if participant is a minor.' -%>
        <%= f.text_field  :name -%>
      <% end -%>

      <%- if @business.business_config.ask_for_phonenumber? %>
        <%= f.label :phone_number, 'Phone Number' %>
        <%= f.phone_field  :phone_number %>
      <% end %>

      <%- if @business.business_config.ask_for_emergency_number? %>
        <%= f.label :emergency_phone_number, 'Emergency contact phone number *' %>
        <%= f.phone_field  :emergency_phone_number %>
      <% end %>

      <%- if @business.business_config.ask_for_helmet_waiver? %>
        <%= f.label :ask_for_helmet_waiver, 'I have been encouraged to use a bicycle helmet, and I decline using the helmet during this ride.*' %>
        <%= f.text_field  :helmet_waiver %>
      <% end %>

      <%= f.label :email, 'Email' -%>
      <%= f.email_field :email -%>


    </div>
  </div>

  <%- if @business.business_config.ask_to_join_list? -%>
  <div class="row-fluid">
    <div class="span12">
      <label class="checkbox"> <%= f.check_box  :join_list, {:checked=>true} -%> Join Mail List
	    <%= @business.business_config.join_list_description -%>
	    </label>
    </div>
  </div>
  <% end -%>

  <div class="row-fluid">
    <div class="span12">
      <%= f.submit 'Next', :class => 'btn btn-large btn-danger' %>
    </div>
  </div>

  <% end -%>
  <br/>
  <hr/>
  <small class="pull-left">powered by</small>
  <%= link_to("", "http://www.mightbuy.it", class: 'logo-small', target: '_blank') -%>
</div>

app/views/retail_leads/new_add_list.html.erb
<div class="release-liability clearfix">
  <%= form_for @lead, url: retail_leads_path, remote: true, method: :post, html: {multipart: true, id: "photo-form"} do |f| -%>
    <div class="row-fluid">
      <div class="span12">
        <%= link_to("Logout", destroy_business_staff_session_path, method: :delete, class: 'btn btn-danger pull-right') -%>
        <%= image_tag(business_form_logo_url_helper(@business), height: 80, class: "img-polaroid pull-left m-right25") -%>
        <h1><%= @business.name -%></h1>
        <h2 >Add another to <%= params[:email] -%></h2>
        <a class="btn btn-danger pull-right" href="/retail_leads/new"> Cancel </a>
      </div>
    </div>
    <%= hidden_field_tag "send_email", 0 -%>
    <%= hidden_field_tag "added", 1 -%>
    <%= hidden_field_tag "list_add", 1 -%>
    <%= f.hidden_field :email, :value=>params[:email] -%>
    <%= f.hidden_field :name, :value=>params[:name] -%>
    <%= f.hidden_field :phone_number, :value=>params[:phone_number] -%>
	

    <div class="row-fluid">
      <div class="span12">
        <div class="well">
          <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
              <td id="lead-photo-preview" valign="center" class="picture">
                &nbsp;
              </td>
            </tr>
          </table>
          <br/>

          <div class="clearfix">
            <div class="row-fluid">
              <div class="span3 hidden-phone">&nbsp;</div>
              <div class="span6 photo-upload">
                <input id="filename" type="text" class="input disabled pull-left visible-desktop" name="filename" readonly>
                <a id="fileselectbutton" class="btn btn-danger pull-left">Take Pic</a>
                <%= f.file_field :photo %>
                <%= f.hidden_field :retained_photo %>
              </div>
              <div class="span3 hidden-phone">&nbsp;</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%- if @business.business_config.include_product_select? -%>
          <div class="row-fluid">
            <div class="span12">
              <%= f.label :product_id, 'Select a Product' -%>
              <%= f.select :product_id, product_list_helper(@business) -%>
            </div>
          </div>
     <% end -%>

    <%- if @business.business_config.ask_for_description? %>
    <div class="row-fluid">
        <div class="span12">
            <%= f.label :message, 'Description' %>
            <%= f.text_area  :message, :rows=>5 %>
         </div>
    </div>
    <% end -%>

    <br/>

    <div class="row-fluid">
      <div class="span12">
        <button class="btn btn-large btn-danger pull-right" type="button" id="photo-email-button" >
          Send Now
        </button>
        <%= f.submit 'Save', class: 'btn btn-large btn-danger', id: "photo-submit-button" %>
      </div>
    </div>
  <% end -%>
  <br/>
  <hr/>
  <small class="pull-left">powered by</small>
  <%= link_to("", "http://www.mightbuy.it", class: 'logo-small', target: '_blank') -%>
</div>

app/views/retail_leads/new_add_photo.html.erb
<div class="release-liability clearfix">
  <%= form_for @lead, url: retail_leads_path, remote: true, method: :post, html: {multipart: true, id: "photo-form"} do |f| -%>
    <div class="row-fluid">
      <div class="span12">
        <%= link_to("Logout", destroy_business_staff_session_path, method: :delete, class: 'btn btn-danger pull-right') -%>
        <%= image_tag(business_form_logo_url_helper(@business), height: 80, class: "img-polaroid pull-left m-right25") -%>
        <h1><%= @business.name -%></h1>
        <h2 >Add another to <%= params[:email] -%></h2>
        <a class="btn btn-danger pull-right" href="/retail_leads/new"> Cancel </a>
      </div>
    </div>
    <%= hidden_field_tag "send_email", 0 -%>
    <%= hidden_field_tag "added", 1 -%>
    <%= f.hidden_field :email, :value=>params[:email] -%>
    <%= f.hidden_field :name, :value=>params[:name] -%>
    <%= f.hidden_field :phone_number, :value=>params[:phone_number] -%>
	

    <div class="row-fluid">
      <div class="span12">
        <div class="well">
          <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
              <td id="lead-photo-preview" valign="center" class="picture">
                &nbsp;
              </td>
            </tr>
          </table>
          <br/>

          <div class="clearfix">
            <div class="row-fluid">
              <div class="span3 hidden-phone">&nbsp;</div>
              <div class="span6 photo-upload">
                <input id="filename" type="text" class="input disabled pull-left visible-desktop" name="filename" readonly>
                <a id="fileselectbutton" class="btn btn-danger pull-left">Take Pic</a>
                <%= f.file_field :photo %>
                <%= f.hidden_field :retained_photo %>
              </div>
              <div class="span3 hidden-phone">&nbsp;</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <%- if @business.business_config.include_product_select? -%>
          <div class="row-fluid">
            <div class="span12">
              <%= f.label :product_id, 'Select a Product' -%>
              <%= f.select :product_id, product_list_helper(@business) -%>
            </div>
          </div>
     <% else -%>
        <%= f.hidden_field :product_id, :value=> product_list_helper(@business).first[1]  -%>
     <% end -%>

    <%- if @business.business_config.ask_for_description? %>
    <div class="row-fluid">
        <div class="span12">
            <%= f.label :message, 'Description' %>
            <%= f.text_area  :message, :rows=>5 %>
         </div>
    </div>
    <% end -%>

    <br/>

    <div class="row-fluid">
      <div class="span12">
        <button class="btn btn-large btn-danger pull-right" type="button" id="photo-email-button" >
          Send Now
        </button>
        <%= f.submit 'Save', class: 'btn btn-large btn-danger', id: "photo-submit-button" %>
      </div>
    </div>
  <% end -%>
  <br/>
  <hr/>
  <small class="pull-left">powered by</small>
  <%= link_to("", "http://www.mightbuy.it", class: 'logo-small', target: '_blank') -%>
</div>

app/views/retail_leads/new_with_photo.html.erb
<div class="new-lead release-liability clearfix">
  <%= form_for @lead, url: retail_leads_path, remote: true, method: :post, html: {multipart: true, id: "photo-form"} do |lead_form| -%>
    <div class="row-fluid">
      <div class="span12">
        <%= link_to("Logout", destroy_business_staff_session_path, method: :delete, class: 'btn btn-danger pull-right') -%>
        <%= image_tag(business_form_logo_url_helper(@business), height: 80, class: "img-polaroid pull-left m-right25") -%>
        <h1><%= @business.name -%></h1>
      </div>
    </div>
    <%= hidden_field_tag "send_email", 0 -%>

    <%= lead_form.fields_for :topics do |topic_form| %>
    <div class="row-fluid">
      <div class="span12">
        <div class="well">
          <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
              <td id="lead-photo-preview" valign="center" class="picture">
                &nbsp;
              </td>
            </tr>
          </table>
          <br/>

          <div class="clearfix">
            <div class="row-fluid">
              <div class="span3 hidden-phone">&nbsp;</div>
              <div class="span6 photo-upload">
                <input id="filename" type="text" class="input disabled pull-left visible-desktop" name="filename" readonly>
                <a id="fileselectbutton" class="btn btn-danger pull-left">Take Pic</a>
                <%= topic_form.file_field :image, class: 'preview-photo-upload' %>
                <%= topic_form.hidden_field :retained_image %>
              </div>
              <div class="span3 hidden-phone">&nbsp;</div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%- if @business.business_config.include_product_select? -%>
      <div class="row-fluid">
        <div class="span12">
          <%= topic_form.label :product_id, 'Select a Product' -%>
          <%= topic_form.select :product_id, product_list_helper(@business) -%>
        </div>
      </div>
    <% end %>
    <% end -%>

    <div class="row-fluid">
      <div class="span12">
        <%- if @business.business_config.ask_for_name? -%>
        <%= lead_form.label :name, 'Name' -%>
        <%= lead_form.text_field  :name -%>
        <% end -%>

        <%- if @business.business_config.ask_for_phonenumber? %>
        <%= lead_form.label :phone_number, 'Phone Number' %>
        <%= lead_form.phone_field  :phone_number %>
        <% end %>


        <%= lead_form.label :email, 'Email' -%>
        <%= lead_form.email_field :email -%>
      </div>
    </div>

    <%- if @business.business_config.ask_to_join_list? -%>
    <div class="row-fluid">
      <div class="span12">
        <label class="checkbox"> <%= lead_form.check_box  :join_list -%> Join Mail List
        <%= @business.business_config.join_list_description -%>
        </label>
      </div>
    </div>
    <% end -%>

    <%- if @business.business_config.ask_for_description? %>
    <div class="row-fluid">
        <div class="span12">
            <%= lead_form.label :message, 'Description' %>
            <%= lead_form.text_area  :message, :rows=>5 %>
         </div>
    </div>
    <% end -%>

    <br/>

    <div class="row-fluid">
      <div class="span12">
        <%= lead_form.submit 'Save', class: 'btn btn-large btn-danger', id: "photo-submit-button", disabled: 'disabled' %>
        <button class="btn btn-large btn-danger pull-right" type="button" id="photo-email-button" disabled="disabled">
          Send Now
        </button>
      </div>
    </div>
  <% end -%>
  <br/>
  <hr/>
  <small class="pull-left">powered by</small>
  <%= link_to("", "http://www.mightbuy.it", class: 'logo-small', target: '_blank') -%>
</div>

<%= render :partial => "modal_confirmaiton" -%>

app/views/retail_leads/photo.html.erb
<div class="new-lead release-liability clearfix">
  <%= form_for @lead, url: retail_lead_path(@lead), remote: true,method: :put, html: {multipart: true, id: "photo-form"} do |lead_form| -%>
    <div class="row-fluid">
      <div class="span12">
        <%= image_tag(business_form_logo_url_helper(@business), height: 80, class: "img-polaroid pull-left m-right25") -%>
        <%= link_to("Logout", destroy_business_staff_session_path, method: :delete, class: 'btn btn-danger pull-right') -%>
		<br><br>
         <%= link_to('No Picture', new_retail_lead_path, class: 'btn btn-danger pull-right') -%>

        <h1><%= @business.name -%></h1>
      </div>
    </div>
    <%= hidden_field_tag "send_email", 0 -%>

    <%= lead_form.fields_for :topics do |topic_form| %>
	    <div class="row-fluid">
	      <div class="span12">
	        <div class="well">
	          <table border="0" cellpadding="0" cellspacing="0" width="100%">
	            <tr>
	              <td id="lead-photo-preview" valign="center" class="picture">
	                &nbsp;
	              </td>
	            </tr>
	          </table>
	          <br/>

	          <div class="clearfix">
	            <div class="row-fluid">
	              <div class="span3 hidden-phone">&nbsp;</div>
	              <div class="span6 photo-upload">
	                <input id="filename" type="text" class="input disabled pull-left visible-desktop" name="filename" readonly>
	                <a id="fileselectbutton" class="btn btn-danger pull-left">Take Pic</a>
	                <%= topic_form.file_field :image, class: 'preview-photo-upload' %>
	                <%= topic_form.hidden_field :retained_image %>
	              </div>
	              <div class="span3 hidden-phone">&nbsp;</div>
	            </div>
	          </div>
	        </div>
	      </div>
	    </div>
    

	    <%- if @business.business_config.include_product_select? -%>
	          <div class="row-fluid">
	            <div class="span12">
	              <%= topic_form.label :product_id, 'Select a Product' -%>
	              <%= topic_form.select :product_id, product_list_helper(@business) -%>
	            </div>
	          </div>
	    <% end %>
    <% end -%>

    <%- if @business.business_config.ask_for_description? %>
    <div class="row-fluid">
        <div class="span12">
            <%= lead_form.label :message, 'Description' %>
            <%= lead_form.text_area  :message, :rows=>5 %>
         </div>
    </div>
    <% end -%>
    <br/>

    <div class="row-fluid">
      <div class="span12">
        <%= lead_form.submit 'Save', class: 'btn btn-large btn-danger', id: "photo-submit-button" %>
        <button class="btn btn-large btn-danger pull-right" type="button" id="photo-email-button">
          Send Now
        </button>
      </div>
    </div>
  <% end -%>
  <br/>
  <hr/>
  <small class="pull-left">powered by</small>
  <%= link_to("", "http://www.mightbuy.it", class: 'logo-small', target: '_blank') -%>
</div>

<%= render :partial => "modal_confirmaiton" -%>

app/views/retail_leads/update.js.erb
$("#flash-notifications").html("<%= escape_javascript(render partial: 'shares/notifications') -%>");
<%- flash.clear -%>

<% if @lead.errors.empty? -%>
  $(".saving-loader").hide();
  $("#lead-confirmation").modal().center();
<% end -%>

$('div.release-liability').after("<%= raw escape_javascript( render :partial => 'modal_confirmaiton', :locals => {:lead => @lead} ) %>");


$('#lead-confirmation').modal().center();