config/routes.rb
MightbuyBusiness::Application.routes.draw do
  devise_for :business_staffs, controllers: {
      registrations: 'registrations'
  }

  resource :business do
    collection do
      get :complete_profile
      get :profile
      put :update_profile
    end
    resources :business_staffs, module: "business"
  end

  resources :products do
    resource :deal
  end

  resources :topics

  resources :timeline
  resources :customers
  resources :leads do
    resources :topics, only: [:destroy]
  end

  resource  :retail
  resources :retail_leads do
    get 'photo', on: :member
  end
  resource  :business_config, only: [:edit, :update]

  root :to => "welcome#index"
  match "/contact" => "welcome#contact"
  match "/about" => "welcome#about"
  match "/terms" => "welcome#terms"
  match "/pricing" => "welcome#pricing"
  match "/help" => "welcome#help"

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :find_business
  layout 'business_with_sidebar'

  def index
    products = Product.find(:all, conditions: {
      business_id: @business.id
    }, order: sort_column + ' ' + sort_direction)

    @products = Kaminari.paginate_array(products).page(params[:page]).per(10)
    @product = Product.new()
  end

  def create
    @product = Product.new(params[:product])
    @product.business = @business
    if @product.save
      flash[:notice] = "Product saved"
    else
      flash[:error] = @product.errors.full_messages.join(" ")
    end
    redirect_to products_path
  end

  def edit
    @product = @business.find_and_update_product(params[:id])
    unless @product
      render nothing: true
    end
  end

  def update
    @product = @business.find_and_update_product(params[:id])
  end

  def destroy
    @product = @business.products.find_by_id(params[:id])
    if @product && @product.destroy
      flash[:notice] = "Product deleted"
    else
      flash[:error] = "You can not remove products linked with users"
    end
    redirect_to products_path
  end


  protected
    def sort_direction
      if %w[asc desc].include?(params[:direction])
        params[:direction]
      else
        'asc'
      end
    end

    def sort_column
      if Product.column_names.include?(params[:direction])
        params[:direction]
      else
        'name'
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_product.html.erb
<td colspan="5" class="add-deal">
  <%= form_for(@product, html: { class: "form-horizontal"} ) do |f| -%>
    <legend>
      Add a New Product
    </legend>
    <div class="row">
      <div class="span8">
        <div class="control-group">
          <label class="control-label">Product Name:</label>

          <div class="controls">
            <%= f.text_field :name, class: "span3" -%>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label">URL:</label>

          <div class="controls">
            <%= f.text_field :url, class: "span3" -%>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label">List Price:</label>

          <div class="controls">
            <%= f.text_field :price, class: "span3" -%>
          </div>
        </div>
        <div class="control-group">
          <div class="controls m-top5">
            <%= f.submit("Save Product", class: "btn btn-danger", :id => "save-product") -%>
            <a href="javascript:void(0)" class="btn btn-danger m-left5 product-create-cancel"> Cancel </a>
          </div>
        </div>
      </div>
  <% end -%>
</td>

app/views/products/_edit_form.html.erb
<tr id="edit-product-<%= @product.id -%>" class="edit-product-row">
  <td colspan="5" class="add-deal">
    <%= form_for(@product, remote: true,html: {class: "form-horizontal"}) do |f| -%>
      <legend>
        Update the product
      </legend>
      <div class="row">
        <div class="span8">
          <div class="control-group">
            <label class="control-label">Product Name:</label>

            <div class="controls">
              <%= f.text_field :name, class: "span3" -%>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">URL:</label>

            <div class="controls">
              <%= f.text_field :url, class: "span3" -%>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">List Price:</label>

            <div class="controls">
              <%= f.text_field :price, class: "span3" -%>
            </div>
          </div>
          <div class="control-group">
            <div class="controls m-top5">
              <%= f.submit("Save Product", class: "btn btn-danger") -%>
              <a href="javascript:void(0)" class="btn btn-danger m-left5 product-edit-cancel"> Cancel </a>
            </div>
          </div>
        </div>
    <% end -%>
  </td>
</tr>

app/views/products/_product_line.html.erb
<td>
  <%= link_to(product.url, product.url, :target=> "_blank") -%>
</td>
<td>
  <%= product.name -%>
</td>
<td>
  <%= product.topics.count -%>
</td>
<td class="product-deals">
  <%- if product.bargin -%>
    <%= link_to 'Edit Deal', edit_product_deal_path(product), remote: true, class: "btn btn-danger btn-mini m-left10 add-deal-button" -%>
  <% else -%>
    <button class="btn btn-danger btn-mini m-left10 add-deal-button" data-product-id="<%= product.id -%>">
      Add Deal
    </button>
  <% end -%>
</td>
<td>
  <%= link_to(edit_product_path(product), class: "btn btn-mini", remote: true) do -%>
    <i class="icon-pencil"></i>
  <% end -%>
  <%= link_to(product_path(product), method: :delete, class: 'btn btn-mini btn-danger') do -%>
    <i class="icon-remove icon-white"></i>
  <% end -%>
</td>

app/views/products/edit.js.erb
$("#product-<%= @product.id %>").after("<%= escape_javascript(render :partial => 'edit_form') -%>");

app/views/products/index.html.erb
<div class="span9 bg-dark unevenheights">
  <h3 class="page-title align-right"> Products added by website URL </h3>

  <div class="table-container">
    <div class="table-header clearfix">
      <button class="btn btn-small btn-danger pull-right add-product-btn">
        Add Products
      </button>
      <div class="title">
        Products
      </div>
    </div>
    <table class="table">
      <tr class="add-product-row hide">
        <%= render :partial => "add_product" -%>
      </tr>
      <tr class="product-heading">
        <th>
            <%= link_to_sort('URL', :url) %>
        </th>
        <th>
            <%= link_to_sort('Product Name', :name) %>
        </th>
        <th>Interested Buyers</th>
        <th>Available Deal</th>
        <th>Edit/Delete</th>
      </tr>
      <% @products.each do |product| -%>
        <tr class="product-row" id="product-<%= product.id -%>">
          <%= render :partial => "product_line", locals: {product: product} -%>
        </tr>
      <% end -%>
    </table>
    <div class="table-footer clearfix">
      <%= paginate @products, :theme => 'mightbuy_theme' -%>
    </div>
  </div>
</div>

app/views/products/update.js.erb
<% if @product && @product.update_attributes!(params[:product]) -%>
  $("#product-<%= @product.id -%>").html("<%= escape_javascript(render :partial => 'product_line', locals: {product: @product}) -%>")

$(".saving-loader").show().delay(300).hide(200);
$("#flash-notifications").delay(1000).html("<%= escape_javascript(render partial: 'shares/notifications') -%>");
$("#flash-notifications").show().delay(6000).fadeOut(500);


<% end -%>
<% if @product -%>
  $("#edit-product-<%= @product.id -%>").remove();
<% end -%>